name: "SCA Scan"
description: "Run SCA scan and generate vulnerability reports"

inputs:
  repository-name:
    description: 'The name of the repository to use for the report filename.'
    required: true
  run_vet:
    description: 'Whether to run vet scan'
    required: false
    default: 'false'
  slack_token:
    description: 'Slack bot token'
    required: true
  slack_channel:
    description: 'Slack channel ID'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

outputs:
  has_findings:
    description: "Indicates if the scan found any issues"
    value: ${{ steps.extract_high_critical_vulnerabilities.outputs.found }}

runs:
  using: "composite"
  steps:
    - name: Detect SBOM Path
      id: detect_path
      shell: bash
      run: |
        case "${{ inputs.application_type }}" in
          "node")
            if [ -f "package.json" ] || [ -f "package-lock.json" ] || [ -f "yarn.lock" ]; then
              echo "sbom_path=./" >> $GITHUB_OUTPUT
            else
              echo "sbom_path=./" >> $GITHUB_OUTPUT
            fi
            ;;
          "python")
            if [ -f "requirements.txt" ] || [ -f "pyproject.toml" ] || [ -f "setup.py" ] || [ -f "Pipfile" ] || [ -f "poetry.lock" ]; then
              echo "sbom_path=./" >> $GITHUB_OUTPUT
            else
              echo "sbom_path=./" >> $GITHUB_OUTPUT
            fi
            ;;
          "php")
            if [ -f "src/composer.json" ] || [ -f "src/composer.lock" ] || [ -f "src/package.json" ]; then
              echo "sbom_path=src/" >> $GITHUB_OUTPUT
            elif [ -f "composer.json" ] || [ -f "composer.lock" ] || [ -f "package.json" ] || [ -f "package-lock.json" ]; then
              echo "sbom_path=./" >> $GITHUB_OUTPUT
            else
              echo "sbom_path=./" >> $GITHUB_OUTPUT
            fi
            ;;
          *)
            echo "sbom_path=./" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: Run vet
      id: vet
      if: inputs.run_vet == 'true'
      uses: safedep/vet-action@a8b4e46b0a0fdb3709029cff5fb158e935baa010
      with:
        policy: ${{ github.ref_name == 'main' && '.github/vet/production-policy.yml' || '.github/vet/staging-policy.yml' }}
        exception-file: .github/vet/exceptions.yml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Generate SBOM
      id: sbom
      uses: anchore/sbom-action@cee1b8e05ae5b2593a75e197229729eabaa9f8ec
      with:
        format: spdx-json
        path: ${{ github.workspace }}/${{ steps.detect_path.outputs.sbom_path }}
        upload-artifact: false
        output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

    - name: Run vulnerability scan
      id: scan
      continue-on-error: true
      uses: anchore/scan-action@16910ac423301c6d30554b83a7f71ac6ff4a51f3
      with:
        sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
        fail-build: false
        severity-cutoff: high
        only-fixed: true
        output-format: table
        output-file: ${{ github.event.repository.name }}-sca-report.txt

    - name: Extract High/Critical Vulnerabilities
      id: extract_high_critical_vulnerabilities
      shell: bash
      run: |
        report="${{ github.event.repository.name }}-sca-report"
        if [ ! -f "${report}.txt" ]; then
          echo "Scan report ${report}.txt not found!"
          echo "found=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        (head -n 1 "${report}.txt" && grep -Ei "HIGH|CRITICAL" "${report}.txt" || true) > "${{ github.event.repository.name }}-sca-report-filtered.txt"
        if grep -qEi "HIGH|CRITICAL" "${report}.txt"; then
          echo "found=true" >> $GITHUB_OUTPUT
        else
          echo "found=false" >> $GITHUB_OUTPUT
        fi
        ls "${{ github.event.repository.name }}-sca-report-filtered.txt"

    - name: Share SCA Report to Slack
      if: steps.extract_high_critical_vulnerabilities.outputs.found == 'true'
      uses: ./.github/actions/slack-feedbacks@main
      with:
        txt_file: ${{ github.event.repository.name }}-sca-report-filtered.txt
        report_name: ${{ inputs.repository-name }}
        slack_token: ${{ inputs.slack_token }}
        slack_channel: ${{ inputs.slack_channel }}
        report_type: sca

    - name: Fail on vulnerabilities
      id: fail_on_vulnerabilities
      if: steps.extract_high_critical_vulnerabilities.outputs.found == 'true'
      shell: bash
      run: |
        if grep -qEi "HIGH|CRITICAL" "${{ github.event.repository.name }}-sca-report.txt"; then
          echo "::error::There are high/critical vulnerabilities packages in the code"
          exit 1
        fi