name: "Slack Report"
description: "Send findings to Slack"

inputs:
  mentions:
    required: true
    description: "Slack user mentions"
  txt_file:
    required: true
    description: "Path to the text file to upload"
  report_name:
    required: true
    description: "Name of the report"
  slack_token:
    required: true
    description: "Slack bot token"
  slack_channel:
    required: true
    description: "Slack channel ID"
  description:
    required: false
    default: "Security findings detected"
    description: "Description to include in the Slack message"
  report_type:
    required: false
    default: "sca"
    description: "Type of report (sast or sca)"

runs:
  using: "composite"
  steps:
    - name: Get commit info
      id: meta
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
        echo "author_login=${{ github.actor }}" >> $GITHUB_OUTPUT
        echo "author_name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
        echo "committer_name=$(git log -1 --pretty=format:'%cn')" >> $GITHUB_OUTPUT

    - name: Build Slack Mentions
      id: slack_mentions
      shell: bash
      run: |
        REPO_NAME="${{ github.repository }}"

        declare -A MAP
        declare -a FALLBACK_ARRAY

        if [[ "$REPO_NAME" == *"devfest"* ]]; then
          MAP["saintmalik"]="U06CWR1J58T"
          FALLBACK_ARRAY=("saintmalik")
        else
          MAP["saintmalik"]="U06CWR1J58T"
          FALLBACK_ARRAY=("saintmalik")
        fi

        AUTHOR="${{ steps.meta.outputs.author_login }}"
        COMM="${{ steps.meta.outputs.committer_name }}"
        MENTION_LIST=""

        if 
          if [[ -n "${MAP[$AUTHOR]}" ]]; then
            MENTION_LIST+="<@${MAP[$AUTHOR]}> "
          fi
          if [[ "$AUTHOR" != "$COMM" && -n "${MAP[$COMM]}" ]]; then
            MENTION_LIST+="<@${MAP[$COMM]}> "
          fi
          MENTION_LIST=$(echo "$MENTION_LIST" | sed 's/ *$//')

          if [[ -z "$MENTION_LIST" ]]; then
            RANDOM_USER=${FALLBACK_ARRAY[$RANDOM % ${#FALLBACK_ARRAY[@]}]}
            MENTION_LIST="<@${MAP[$RANDOM_USER]}>"
          fi
        fi

        echo "mentions=$MENTION_LIST" >> $GITHUB_OUTPUT

    - name: Set report type uppercase
      id: report_type
      shell: bash
      run: |
        echo "upper=$(echo '${{ inputs.report_type }}' | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT

    - name: Upload to Slack
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a #v2.1.1
      with:
        method: files.uploadV2
        token: ${{ inputs.slack_token }}
        payload: |
          channel_id: ${{ inputs.slack_channel }}
          initial_comment: "Hello ${{ steps.slack_mentions.outputs.mentions }}! 👋 ${{ steps.report_type.outputs.upper }} findings in ${{ inputs.report_name }} need fixing before deployment. You've got this! 💪"
          file: "${{ inputs.txt_file }}"
          filename: "${{ inputs.report_name }}-${{ inputs.report_type }}-${{ steps.meta.outputs.sha_short }}.txt"