name: "Secret Scan"
description: "Scan for hardcoded credentials and secrets in codebase"

inputs:
  github_token_gitleaks:
    description: 'GitHub token for authentication'
    required: true
  gitleaks_license:
    description: 'Gitleaks license key'
    required: false
  devsecops_slack_webhook:
    description: 'Slack webhook URL for notifications'
    required: false
  current_branch:
    description: 'Current branch name'
    required: true
  commit_message:
    description: 'Current commit message'
    required: false
    default: 'No commit message provided'
  only_verified:
    description: 'Only scan for verified secrets'
    required: false
    default: 'true'
  send_slack_notification:
    description: 'Send Slack notification on failure'
    required: false
    default: 'true'
  enable_gitleaks:
    description: 'Enable Gitleaks scanning'
    required: false
    default: 'true'
  enable_trufflehog:
    description: 'Enable TruffleHog scanning'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Scan for secrets with Gitleaks
      id: gitleaks
      if: inputs.enable_gitleaks == 'true'
      continue-on-error: true
      uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7
      env:
        GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
        GITHUB_TOKEN: ${{ inputs.github_token_gitleaks }}
        GITLEAKS_LICENSE: ${{ inputs.gitleaks_license }}

    - name: Scan for secrets with TruffleHog
      id: trufflehog
      if: inputs.enable_trufflehog == 'true'
      continue-on-error: true
      uses: trufflesecurity/trufflehog@6641d4ba5b684fffe195b9820345de1bf19f3181
      with:
        path: ./
        base: ""
        head: ${{ inputs.current_branch }}
        extra_args: --log-level=2 ${{ inputs.only_verified == 'true' && '--results=verified' || '--results=verified,unknown' }}

    - name: Send Slack notification if secrets found
      if: (steps.gitleaks.outcome == 'failure' || steps.trufflehog.outcome == 'failure') && inputs.send_slack_notification == 'true' && inputs.devsecops_slack_webhook != ''
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a  #v2.1.1
      with:
        webhook-type: incoming-webhook
        webhook: ${{ inputs.devsecops_slack_webhook }}
        payload: |
          {
            "text": "🚨 Hardcoded credentials detected in the codebase! 🚨",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*🚨 Hardcoded Credentials Detected!* \n\nWhy? You've push hardcoded creds again. We need to clean up the commits, haaaa 😱"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${{ inputs.current_branch }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n${{ github.workflow }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit Message:*\n${{ inputs.commit_message }}"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Status: *Secrets Detected* :warning:"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Workflow Run",
                      "emoji": true
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }