name: "Generate and Check Report"
description: "Generates an AI report and checks for findings."

inputs:
  repository-name:
    description: 'The name of the repository to use for the report filename.'
    required: true
  sast-recommend-uri:
    description: 'D1 API key for AI report generation.'
    required: true
  deepseek_api_key:
    description: 'DeepSeek API key for AI report generation.'
    required: true

outputs:
  has_findings:
    description: "Indicates if the scan found any issues"
    value: ${{ steps.check.outputs.has_findings }}
  report_json_file:
    description: 'The name of the generated JSON report file.'
    value: ${{ steps.devsec.outputs.report_json_file }}
  report_md_file:
    description: 'The name of the generated Markdown report file.'
    value: ${{ steps.devsec.outputs.report_md_file }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4
      with:
        node-version: 20

    - name: Generate Report
      id: devsec
      shell: bash
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        D1_DATABASE_ID: ${{ inputs.d1_database_id }}
        sast-recommend-uri: ${{ inputs.sast-recommend-uri }}
        DEEPSEEK_API_KEY: ${{ inputs.deepseek_api_key }}
      run: |
        ls -la
        cd reports/ && ls -la && yarn install && cd ..
        OPENGREP_FILE="${{ inputs.repository-name }}-opengrep.json"
        JSON_FILE="${{ inputs.repository-name }}-sast-github-action.json"
        MD_FILE="${{ inputs.repository-name }}-sast-github-action.md"
        cp "$OPENGREP_FILE" "$JSON_FILE"
        node reports/reports.js "$JSON_FILE" "$MD_FILE"
        echo "report_json_file=$JSON_FILE" >> $GITHUB_OUTPUT
        echo "report_md_file=$MD_FILE" >> $GITHUB_OUTPUT

    - name: Check Findings
      id: check
      shell: bash
      run: |
        JSON_FILE="${{ inputs.repository-name }}-sast-github-action.json"
        MD_FILE="${{ inputs.repository-name }}-sast-github-action.md"

        # The check for findings should probably be on the JSON file, which is more reliable.
        # However, to match the original logic, we will stick to the Markdown file.
        # A more robust check might be: `jq '.results[] | length' -e "$JSON_FILE"`

        findings=$(grep 'Total Raw Findings:' "$MD_FILE" | awk '{print $5}')
        echo "ðŸ” Total Raw Findings: $findings"

        if [ "$findings" -eq 0 ]; then
          echo "has_findings=false" >> $GITHUB_OUTPUT
        else
          echo "has_findings=true" >> $GITHUB_OUTPUT
        fi